kind: Service
apiVersion: v1
metadata:
  name: smartbids-backend
  labels:
    name: smartbids-backend
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: smartbids-backend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartbids-backend
spec:
  selector:
    matchLabels:
      app: smartbids-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: smartbids-backend
    spec:
      containers:
        - name: smartbids-backend
          image: lmsamarawickrama/smartbids-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: BROKER_HOST
              valueFrom:
                configMapKeyRef:
                  name: broker-conf
                  key: host
            - name: BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: broker-conf
                  key: port
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-credentials
                  key: username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-credentials
                  key: password